// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class calendarUI : UIView
	{
		public calendarUI (IntPtr handle) : base (handle)
		{
		}
	}
}
