// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class calendarViewController : UIViewController
	{
		public calendarViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad(){
		}
	}
}
