// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class classStandingView : UIViewController
	{
		public classStandingView (IntPtr handle) : base (handle)
		{
		}


		private class CustomTheme : TrackBeamTheme
		{
			//Change the BaseTintColor
			public override string PhoneBackgroundName
			{
				get
				{
					return "background_blur.jpg";
				}
			}



		}

		public override void ViewWillAppear (bool animated)
		{
			//ThemeManager.Current.Apply(View);
			/*ThemeManager.Current.Apply (nameRegBox);
			ThemeManager.Current.Apply (emailRegBox);
			ThemeManager.Current.Apply(schoolRegBox);
			ThemeManager.Current.Apply(passRegBox);
			ThemeManager.Current.Apply(confirmpassRegBox);*/
			NavigationController.NavigationBarHidden = false;

			ThemeManager.Register<CustomTheme>().Apply(View);

			base.ViewWillAppear (animated);
		}

	}
}
