// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class Dashboardview : UIViewController
	{
		public Dashboardview (IntPtr handle) : base (handle)
		{
		}

		private class CustomTheme : TrackBeamTheme
		{
			//Change the BaseTintColor
			public override string PhoneBackgroundName
			{
				get
				{
					return "background_blur.jpg";
				}
			}


		}


		public override void ViewWillAppear (bool animated)
		{
			//ThemeManager.Current.Apply(View);


			ThemeManager.Register<CustomTheme>().Apply(View);
			//ThemeManager.Register<CustomTheme>().Apply(dashLbl);

			if (AccountType.type == "student") {

				dashLabel.Text = "MY GRADE";

				commBtn.SetTitle ("Ask the Professor", UIControlState.Normal);

				scheduleBtn.SetTitle ("My Schedule", UIControlState.Normal);

				profTipsBtn.SetTitle ("My Assignments", UIControlState.Normal);

				classStngBtn.SetTitle ("Class Standing", UIControlState.Normal);
			}

			if (AccountType.type == "parent") {

				dashLabel.Text = "MY CHILD'S GRADE";

				commBtn.SetTitle ("Ask the Professor", UIControlState.Normal);

				scheduleBtn.SetTitle ("My Child Standing", UIControlState.Normal);

				profTipsBtn.SetTitle ("Professor Tips", UIControlState.Normal);

				classStngBtn.SetTitle ("My Child HW", UIControlState.Normal);
			}

			if (AccountType.type == "professor") {

				dashLabel.Text = "MY CLASS";

				commBtn.SetTitle ("Talk to the Students", UIControlState.Normal);

				scheduleBtn.SetTitle ("Class Schedule", UIControlState.Normal);

				profTipsBtn.SetTitle ("Assignments", UIControlState.Normal);

				classStngBtn.SetTitle ("Class Standing", UIControlState.Normal);
			}


			base.ViewWillAppear (animated);
		}
	}
}
