// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class LogInViewController : UIViewController
	{
		public LogInViewController (IntPtr handle) : base (handle)
		{
		}


		private class CustomTheme : TrackBeamTheme
		{
			//Change the BaseTintColor
			public override string PhoneBackgroundName
			{
				get
				{
					return "background_blur.jpg";
				}
			}


		
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			logInButton.TouchUpInside += (object sender, EventArgs e) => {

				if(!string.IsNullOrEmpty(emailLogInBox.Text) && !string.IsNullOrEmpty(passLogInBox.Text)) {
					
					string lan = "en";
					if (
						emailLogInBox.Text == "atlsaber@gmail.com"){
						lan = "es";
					}

					AppDelegate.LoggedUser = new iOSsample.User() {Username = emailLogInBox.Text, LastMessagesRead = DateTime.Now,Language = lan };

					NavigationController.PushViewController(Storyboard.InstantiateViewController("DashboardviewID")
						,true);
				}

			};
		}

		public override void ViewWillAppear (bool animated)
		{
			//ThemeManager.Current.Apply(View);
			/*ThemeManager.Current.Apply (nameRegBox);
			ThemeManager.Current.Apply (emailRegBox);
			ThemeManager.Current.Apply(schoolRegBox);
			ThemeManager.Current.Apply(passRegBox);
			ThemeManager.Current.Apply(confirmpassRegBox);*/
			NavigationController.NavigationBarHidden = false;

			ThemeManager.Register<CustomTheme>().Apply(View);
			ThemeManager.Current.Apply(logInButton);

			base.ViewWillAppear (animated);
		}



	}
}
