// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class RegisterViewController : UIViewController
	{
		public RegisterViewController (IntPtr handle) : base (handle)
		{
		}



		public override void ViewWillAppear (bool animated)
		{
			//ThemeManager.Current.Apply(View);
			/*ThemeManager.Current.Apply (nameRegBox);
			ThemeManager.Current.Apply (emailRegBox);
			ThemeManager.Current.Apply(schoolRegBox);
			ThemeManager.Current.Apply(passRegBox);
			ThemeManager.Current.Apply(confirmpassRegBox);*/
			ThemeManager.Current.Apply(regButton);

			base.ViewWillAppear (animated);
		}
	}
}
