// This file has been autogenerated from a class added in the UI designer.

using System;
using Xamarin.Themes;
using Xamarin.Themes.Core;
using Xamarin.Themes.TrackBeam;
using Foundation;
using UIKit;

namespace Mystro.iOS
{
	public partial class RegisterViewController : UIViewController
	{
		public RegisterViewController (IntPtr handle) : base (handle)
		{
		}


		private class CustomTheme : TrackBeamTheme
		{
			//Change the BaseTintColor
			public override string PhoneBackgroundName
			{
				get
				{
					return "background_blur.jpg";
				}
			}


		}


		public override void ViewWillAppear (bool animated)
		{
			//ThemeManager.Current.Apply(View);


			ThemeManager.Register<CustomTheme>().Apply(View);
			ThemeManager.Current.Apply(regButton);

			base.ViewWillAppear (animated);
		}
	}
}
